
export default {
    jwtSecret: Buffer.from(process.env.JWT_SECRET, 'base64'),
    jwtPublic: Buffer.from(process.env.JWT_PUB, 'base64'),
    jwtLife: process.env.JWT_LIFE,
    jwtRefreshSecret: Buffer.from(process.env.JWT_REFRESH_SECRET, 'base64'),
    jwtRefreshPublic: Buffer.from(process.env.JWT_REFRESH_PUB, 'base64'),
    jwtRefreshLife: process.env.JWT_REFRESH_LIFE,
    verificationCodeLife: process.env.VERIFICATION_CODE_LIFE,
    mlServiceURL: process.env.ML_URL,
    mlServicePublicURL: process.env.ML_PUBLIC_URL,
    audioFolder: process.env.AUDIO_SHARE_DIR,
    photoFolder: process.env.PHOTO_SHARE_DIR,
    voiceFolder: process.env.VOICE_SHARE_DIR,
    coughValidationFolder: process.env.COUGH_VALIDATION_DIR,
    voiceComparisonFolder: process.env.VOICE_COMPARISON_DIR,
    hwDiagnosticAudioFolder: process.env.HW_DIAGNOSTIC_AUDIO_DIR,
    dataset_audio_folder: process.env.DATASET_AUDIO_FOLDER,
    datasetSpectreFolder: process.env.DATASET_SPECTRE_FOLDER,
    spectreFolder: process.env.SPECTRE_FOLDER,
    hl7Folder: process.env.HL7_FOLDER,
    s3Bucket: process.env.S3_BUCKET,
    mlServiceTimeout: 120000,
    tgBotAudioFolder: process.env.TG_BOT_AUDIO_DIR,
    tgBotPublicUrl: process.env.TG_BOT_PUBLIC_ENDPOINT,
    tgBotToken: process.env.TG_BOT_TOKEN,
    datasetBotAudioFolder: process.env.DATASET_BOT_AUDIO_DIR,
    datasetBotPublicUrl: process.env.DATASET_BOT_PUBLIC_ENDPOINT,
    datasetBotToken: process.env.DATASET_BOT_TOKEN,
    diagnosticBotAudioFolder: process.env.DIAGNOSTIC_BOT_AUDIO_DIR,
    diagnosticBotPublicUrl: process.env.DIAGNOSTIC_BOT_PUBLIC_ENDPOINT,
    diagnosticBotToken: process.env.DIAGNOSTIC_BOT_TOKEN,
    muusBotAudioFolder: process.env.MUUS_BOT_AUDIO_DIR,
    muusBotPublicUrl: process.env.MUUS_BOT_PUBLIC_ENDPOINT,
    muusBotToken: process.env.MUUS_BOT_TOKEN,
    notifyDiagnosticBotPublicUrl: process.env.NOTIFY_DIAGNOSTIC_BOT_PUBLIC_ENDPOINT,
    notifyDiagnosticBotToken: process.env.NOTIFY_DIAGNOSTIC_BOT_TOKEN,
    registerWebhook: process.env.REGISTER_WEBHOOK === 'true',
    sftpHost: process.env.SFTP_HOST,
    sftpPort: process.env.SFTP_PORT,
    sftpUsername: process.env.SFTP_USERNAME,
    sftpPassword: process.env.SFTP_PASSWORD,
    sftpUploadFolder: process.env.SFTP_UPLOAD_FOLDER,
    fileAccessProtocol: process.env.FILE_ACCESS_PROTOCOL,
    doctorNotificationType: process.env.DOCTOR_NOTIFICATION_TYPE
};
